# Generated by Django 5.0.4 on 2024-05-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_delete_person_delete_users'),
    ]

    operations = [

        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('route_description', models.CharField(blank=True, max_length=100, null=True)),
                ('route_alt_description', models.CharField(blank=True, max_length=100, null=True)),
                ('stamp_date', models.DateTimeField(auto_now_add=True)),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Regions')),
                ('user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
